var animais = ['CACHORRO', 'GATO', 'FOCA', 'GALINHA', 'PINGUIM', 'BODE', 'OVELHA', 'ZEBRA', 'CROCODILO',
 'MACACO', 'PORCO', 'RATO', 'ESQUILO', 'GUAXINIM', 'URSO', 'RINOCERONTE', 'BALEIA', 'IGUANA', 'EMA', 
 'GOLFINHO', 'FLAMINGO', 'ELEFANTE', 'POMBA', 'COELHO', 'LHAMA', 'TIGRE', 'CAVALO', 'LOBO', 'TARTARUGA', 
 'COBRA', 'CAPIVARA', 'PATO', 'LONTRA', 'MAMUTE', 'GIRAFA', 'CORUJA', 'MORCEGO'];

var frutas = ['MELANCIA', 'PERA', 'UVA', 'AMORA', 'BANANA', 'ABACATE', 'MORANGO', 'MANGA', 'ACEROLA',
 'KIWI', 'AMEIXA', 'TANGERINA', 'CAJU', 'COCO', 'ABACAXI', 'CAQUI', 'FIGO', 'GOIABA', 'JACA', 'GRAVIOLA', 
 'PITAYA'];

var objetos = ['BICICLETA', 'CADEIRA', 'POLTRONA', 'MESA', 'GARRAFA', 'CAMA', 'LIVRO', 'CADERNO', 'CANETA',
 'BACIA', 'MOCHILA', 'BOLSA', 'MALA', 'DADO', 'REGADOR', 'TESOURA', 'CHAVE', 'FACA', 'GARFO', 'PRATO', 'CANECA', 
 'COPO', 'TAÇA', 'TELEFONE', 'MEDALHA', 'CHINELO', 'LIXEIRA', 'VASSOURA', 'BORRACHA', 'MOEDA'];